services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=schmuh_quisine'
      - 'POSTGRES_PASSWORD=Schmuh.123'
      - 'POSTGRES_USER=admin'
    ports:
      - "5432:5432"
  #schmuh_quisine_backend:
  #  image: ghcr.io/schmuh-quisine/schmuh_quisine_backend:latest # Replace with your app's image name
  #  container_name: schmuh_quisine_backend
  #  ports:
  #    - "8080:8080" # Map container's port 8080 to host's port 8080
  #  depends_on:
  #    - postgres
