services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=schmuh_quisine'
      - 'POSTGRES_PASSWORD=Schmuh.123'
      - 'POSTGRES_USER=admin'
    ports:
      - "5432:5432"
