spring.application.name=quisine

################## OCR Vars ###########################
ocrPath=/tesseract/tessdata
#ocrPath=src/main/resources/tessdata
testImageFolderPath=src/main/resources/images/test/

################## POSTGRES Vars ######################
spring.datasource.url=jdbc:postgresql://postgres:5432/schmuh_quisine
spring.datasource.username=admin
spring.datasource.password=Schmuh.123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

################# DEBUG ###############################
logging.level.org.springframework.web=DEBUG
logging.level.com.fasterxml.jackson.databind=DEBUG


################# Image Handling Vars ###############################
uploadDir=src/main/resources/images/prod